---
- name: Debian | Install prerequisite packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: "{{ pkg_state }}"
  loop: "{{ prereq_pkgs }}"
  become: true
  register: _pkg
  until: not _pkg.failed
  retries: 3
  delay: 3
...
