---
- name: Delete | import common tasks
  tags:
    - ceph
    - pbos-storage
  ansible.builtin.import_tasks: "common.yml"

- name: Delete | import stop tasks
  tags:
    - ceph
    - pbos-storage
  ansible.builtin.import_tasks: "stop.yml"

- name: Delete | purge rgw packages
  tags:
    - ceph
    - pbos-storage
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
  loop: "{{ rgw_pkgs }}"
  become: true
  when: inventory_hostname in groups['ceph_rgw']

- name: Delete | purge rgw directory
  tags:
    - ceph
    - pbos-storage
  ansible.builtin.file:
    path: "{{ ceph_rgw_dir }}"
    state: absent
  become: true
  when: inventory_hostname in groups['ceph_rgw']

- name: Delete | zap osd device completely
  tags:
    - ceph
    - pbos-storage
  ansible.builtin.shell: >-
    if command -v ceph-volume; then
      ceph-volume lvm zap --destroy {{ item }};
    fi
  become: true
  loop: "{{ ceph_osd_devices }}"
  when: inventory_hostname in groups['ceph_osd']

- name: Delete | unmount ceph tmp volumes
  ansible.builtin.shell: >-
    if grep ceph /proc/mounts; then 
      grep ceph /proc/mounts | cut -d' ' -f2 | xargs umount; 
    fi
  become: true
  when: inventory_hostname in groups['ceph_osd']

- name: Delete | purge osd packages
  tags:
    - ceph
    - pbos-storage
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
  loop: "{{ osd_pkgs }}"
  become: true
  when: inventory_hostname in groups['ceph_osd']

- name: Delete | purge osd directory
  tags:
    - ceph
    - pbos-storage
  ansible.builtin.file:
    path: "{{ ceph_osd_dir }}"
    state: absent
  become: true
  when: inventory_hostname in groups['ceph_osd']

- name: Delete | purge manager packages
  tags:
    - ceph
    - pbos-storage
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
  loop: "{{ mgr_pkgs }}"
  become: true
  when: inventory_hostname in groups['ceph_mgr']

- name: Delete | purge manager directory
  tags:
    - ceph
    - pbos-storage
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  become: true
  loop:
    - "{{ ceph_manager_dir }}"
  when: inventory_hostname in groups['ceph_mgr']

- name: Delete | purge monitor packages
  tags:
    - ceph
    - pbos-storage
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
  loop: "{{ mon_pkgs }}"
  become: true
  when: inventory_hostname in groups['ceph_mon']

- name: Delete | purge monitor directory
  tags:
    - ceph
    - pbos-storage
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  become: true
  loop:
    - "{{ ceph_conf }}"
    - "{{ ceph_client_admin_keyring }}"
    - "{{ ceph_monitor_dir }}"
    - "{{ ceph_client_bootstrap_osd_keyring }}"
  when: inventory_hostname in groups['ceph_mon']

- name: Delete | delete ceph data directory
  tags:
    - ceph
    - pbos-storage
  ansible.builtin.file:
    path: "{{ ceph_data_dir }}"
    state: absent
  become: true
...
