---
- name: OSD | Install osd packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
    allow_unauthenticated: false
  loop: "{{ osd_pkgs }}"
  become: true
  when: inventory_hostname in groups['ceph_osd']

- name: OSD | template configuration
  ansible.builtin.template:
    dest: "{{ ceph_conf }}"
    src: "{{ ansible_distribution | lower }}{{ ceph_conf + '.j2' }}"
    owner: "{{ ceph_user }}"
    group: "{{ ceph_group }}"
    mode: "0644"
  become: true
  when: inventory_hostname in groups['ceph_osd']

- name: OSD | create boostrap-osd directory
  ansible.builtin.file:
    path: "{{ ceph_data_dir }}/bootstrap-osd"
    owner: "{{ ceph_user }}"
    group: "{{ ceph_group }}"
    mode: "0750"
    state: directory
  become: true
  when: inventory_hostname in groups['ceph_osd']

- name: OSD | copy keyrings from the monitor to osd nodes
  ansible.builtin.include_tasks: copy_keyrings.yml
  loop:
    - {path: "{{ ceph_client_admin_keyring }}", mode: "0600"}
    - {path: "{{ ceph_client_bootstrap_osd_keyring }}", mode: "0400"}

- name: OSD | create osd 
  ansible.builtin.shell: >-
    if ! pvs {{ item }} >/dev/null 2>&1; then
      ceph-volume lvm create --data {{ item }}
    fi
  become: true
  loop: "{{ ceph_osd_devices }}"
  when: 
    - inventory_hostname != groups['ceph_mon'][0]
    - is_osd.matched == 0
...
