---
- name: Start | import common tasks
  tags:
    - ceph
    - pbos-storage
  ansible.builtin.import_tasks: "common.yml"

- name: Start | start monitor service
  tags:
    - ceph
    - pbos-storage
  when: inventory_hostname in groups['ceph_mon']
  block:
    - name: Start | start service
      ansible.builtin.service:
        name: "ceph-mon.target"
        state: "started"
      register: _service
      until: _service.state == "started"
      retries: 3
      delay: 3
      become: true
    - name: Start | wait until port is opened
      ansible.builtin.wait_for:
        host: "{{ hostvars[inventory_hostname]['ansible_' + ceph_public_network_iface].ipv4.address }}"
        port: "{{ ceph_mon_port }}"
        sleep: 2
        timeout: 10
        state: started

- name: Start | start manager service
  tags:
    - ceph
    - pbos-storage
  ansible.builtin.service:
    name: "ceph-mgr.target"
    state: "started"
  register: _service
  until: _service.state == "started"
  retries: 3
  delay: 3
  become: true
  when: inventory_hostname in groups['ceph_mgr']

- name: Start | start osd service
  tags:
    - ceph
    - pbos-storage
  ansible.builtin.service:
    name: "ceph-osd.target"
    state: "started"
  register: _service
  until: _service.state == "started"
  retries: 3
  delay: 3
  become: true
  when: inventory_hostname in groups['ceph_osd']
...
