---
- name: systemctl restart service
  service:
    name: "{{ os_systemd_service_name }}.service"
    state: "restarted"
    enabled: true
  register: _restart_service
  until: _restart_service.state == "started"
  retries: 3
  delay: 3
  become: true
  changed_when: false
...
